### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [pimoroni/pxt-scrollbit#17]
Hi @pimoroni,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> 2. Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

Due to it's use of MicroBitFont, there is ongoing to work to look at implementing this which will be tracked in the the `codal-microbit-v2` issue

**Comment by microbit-sam** [comment]
MicroBitFont will be typedef'd in the next CODAL tag
https://github.com/lancaster-university/codal-microbit-v2/pull/32

**Comment by Gadgetoid** [comment]
Thanks for catching this- I'd left my PR in limbo. Should be fixed as of 3aebf31375794a48bd05122066f07a5eafc94cd9

**Comment by microbit-sam** [comment]
Great, we have a daily GH action to test extensions so this should pass tomorrow and I'll close the issue :)

**Comment by Gadgetoid** [comment]
P.S. @microbit-sam while I've got your attention do you have any idea if there's a good example of SPI being used in C++ for a micro:bit extension? I've searched high and low, and can't seem to find the canonical reference. Right now I'm using `SPI` and kinda feeling out how it works by trial and error - this is for: https://github.com/pimoroni/pxt-inkybit/blob/5be7d3aa3b99495afedb8ff6958d9c3268193476/display.cpp#L71

**Comment by microbit-sam** [comment]
Interesting question! I'm not actually sure, I think I've only ever used SPI with a micro:bit to run tests
Currently there's no uBit.spi due to lack of demand and to save pins, but perhaps there ought to be, and only initialise it when required.. If you feel it would be useful, then an issue on https://github.com/lancaster-university/codal-microbit-v2 would be a good way to start a discussion

(You've probably already read through all of the following, but just in case!)

In the DAL (micro:bit V1) the mbed SPI class is used, and documentation can be found here:
https://lancaster-university.github.io/microbit-docs/extras/spi/#spi
https://developer.mbed.org/handbook/SPI

In CODAL (v2) the driver model is here (and should be compatible with the mbed driver):
https://github.com/microbit-foundation/codal-core/blob/master/source/driver-models/SPI.cpp

**Comment by Gadgetoid** [comment]
@microbit-sam Is there a reason this hasn't been picked up as fixed and marked compatible yet? Afaict it's building and I've tested it successfully locally.

**Comment by microbit-sam** [comment]
I've created a PR to renable this in MakeCode
https://github.com/microsoft/pxt-microbit/pull/3818/files

**Comment by microbit-pauline** [comment]
@microbit-sam and @Gadgetoid. We have a ticket raised in support today with a user that purchased a V2 and scroll:bit for Christmas and said that it is not working. I noticed that PR https://github.com/microsoft/pxt-microbit/pull/3818/files is still open, could this be the issue ?

**Comment by microbit-mark** [comment]
Did https://github.com/pimoroni/pxt-scrollbit/pull/15 resolve this issue? If so, we should close here. I've nudged abhijith at MakeCode to review the PR

**Comment by helgibbons** [comment]
v2 and scroll:bit are now working nicely together so am closing this, thanks all!
