### ISSUE TITLE
crashes with error 848 when writing bigger than the screen

### ISSUE THREAD

**Issue by nielsswinkels** [pimoroni/pxt-scrollbit#9]
I create a program that displays any string. As soon as the string reaches the left side of the display it crashes with error 848. Please fix this.

Doesn't matter if I use beta editor or not.

Example code:
https://makecode.microbit.org/_MMUbuaXwza9z

**Comment by nielsswinkels** [comment]
error 848 is related to garbage collector: https://makecode.com/js/errorcodes

**Comment by nielsswinkels** [comment]
Also occurs if the scrollbit is not plugged in.

**Comment by eddhurst** [comment]
Having this exact same issue - I just updated my microbit firmware thinking that might help, but no dice. Nothing fancy, just 


```
basic.forever(function () {
    scrollbit.scrollText("scrolling text goes round and round")
})
```

Gets as far as `scr` and then errors out

**Comment by nielsswinkels** [comment]
My only way around it was going over to micropython, because I was in a hurry to get something working.

**Comment by eddhurst** [comment]
Ah, that's a shame although that was my next port of call, the forums looked like it had a lot more usage with python, figured the library might be better supported.

Looks like it's using v0.0.5 of the JS library - for debugging sakes

**Comment by Gadgetoid** [comment]
A fix has been kindly contributed, so I think this is resolved?

Feel free to re-open and give me an earful if it's still broken in the shipped package.
